apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-worker-config
  namespace: orion-worker
data:
  SERVER_WS: "wss://orion.gitmono.com/ws"
  SCORPIO_BASE_URL: "https://git.gitmono.com"
  SCORPIO_LFS_URL: "https://git.gitmono.com"
  RUST_LOG: "info"

